// groceryzen-angular/src/app/item-search/item-search.component.ts
import { Component, OnInit, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ShoppingListsService, WalmartProductSearchRequest, CreateShoppingListItemRequest } from '../shopping-lists.service';
import { WalmartProductSearchItem } from '../entities/walmart-product-search-item';
import { first } from 'rxjs/operators';

@Component({
  selector: 'app-item-search',
  templateUrl: './item-search.component.html',
  styleUrls: ['./item-search.component.css']
})
export class ItemSearchComponent implements OnInit {
  productItems: WalmartProductSearchItem[];
  productSearchTerm: string;
  showProductItems: boolean;
  shoppingListId: string;

  constructor(
    private route: ActivatedRoute,
    private shoppingListsService: ShoppingListsService,
    private router: Router
  ) { 
    
  }

  ngOnInit() {
    this.productItems = [];
    this.showProductItems = false;
  }

  handleProductSearch(){
    let request = new WalmartProductSearchRequest();
    request.query = this.productSearchTerm;
    this.shoppingListsService.walmartProductSearch(request)
    .pipe(first())
    .subscribe(response => 
    { 
        this.showProductItems = true;
        this.productItems = response.records;
    });
  }  

  handleProductItemSelected(record: WalmartProductSearchItem){
    this.shoppingListId = this.route.snapshot.paramMap.get('id');

    let request = new CreateShoppingListItemRequest();
    request.Completed = false;
    request.Price = record.salePrice;
    request.ProductCategory = record.categoryPath;
    request.ProductName = record.name;
    request.Qty = 1;
    request.ShoppingListId = this.shoppingListId;
    request.UnitPrice = record.salePrice;
    
    this.shoppingListsService.createShoppingListItem(request)
    .pipe(first())
    .subscribe(response => 
    { 
        console.log(response);
        this.productSearchTerm = '';
        this.router.navigateByUrl('/edit-shopping-list/' +  this.shoppingListId);
    });
  }  

  @ViewChild('txtProductSearchTerm') txtProductSearchTerm:ElementRef;

  ngAfterViewInit() {
        setTimeout(() => this.txtProductSearchTerm.nativeElement.focus());
  }

}

<div class="panel panel-default">
  <div class="panel-heading">Item search</div>
  <div class="panel-body">
    <div>
      Search for product:<br>
      <input [(ngModel)]="productSearchTerm" 
             name="txtProductSearchTerm" 
             id="txtProductSearchTerm" 
             #txtProductSearchTerm
             (keyup.enter)="handleProductSearch($event)" 
             />
      <input type="button" value="Search" (click)="handleProductSearch()" class="btn btn-primary" />
    </div>
    <div>
      <table class="table table-striped table-hover" *ngIf="showProductItems">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Unit Price</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let record of productItems">
            <td>
              {{record.name}}<br>
              {{record.categoryPath}}
            </td>
            <td style="text-align:right;">${{record.salePrice}}</td>
            <td>
              <button  (click)="handleProductItemSelected(record)" class="btn btn-primary"> Select </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

// groceryzen-react/src/components/ItemSearch.js
import React, { Component } from 'react';
import axios from 'axios';
import AppEnvironment from './AppEnvironment';

class ItemSearch extends Component {
    constructor(props){
      super(props);
      this.txtSearch = React.createRef();
  
      this.state = {
        records: [],
        shoppingListId: this.props.shoppingListId
      }
    }
  
    onClickSearch() {
      let searchTerm = this.txtSearch.current.value;
      let url = AppEnvironment.getServerRoot() + '/GroceryZen/ListProductsForSearch';
                                                              
      let formData = {
        "Query": searchTerm
      }
  
      axios({
        method: 'post',
        url: url,
        data: formData
      })
      .then(result => this.setState({
        records: result.data.records,
        isLoading: false,
        shoppingListId: this.props.shoppingListId
      }))
      .catch(function (error) {
        console.log(error);
      });
    }
  
    onClickSelectItem(record) {
      
      let url = AppEnvironment.getServerRoot() + '/GroceryZen/CreateShoppingListItem';
      let postData = {
        "ShoppingListId": this.props.shoppingListId,
        "ProductName": record.name,
        "ProductCategory": record.categoryPath,
        "UnitPrice": record.salePrice,
        "Qty": 1,
        "Price": record.salePrice
      };
  
      let component = this;
      let shoppingListId = this.props.shoppingListId;
  
      axios({
        method: 'post',
        url: url,
        data: postData
      })
      .then(function(result) {
        component.props.itemSelected(shoppingListId);
      })
      .catch(function (error) {
        console.log(error);
      });
  
    }
  
    render(){
      const { records, isLoading } = this.state;
  
      this.tableStyle = records.length > 0 ? {display: "block"} : {display: "none"};
  
      if(isLoading){
        return <div>Loading ...</div> 
      }
  
      return (
  
        <div id="divItemSearch">
          <h3>Item Search</h3>
          <div>Enter product search term</div>
          <div>
            <input type="text" id="txtSearch" ref={this.txtSearch}  />
            <button 
              className="btn btn-primary"
              onClick={() => this.onClickSearch() }
            >Search</button>
          </div>
          <table className="table table-striped table-hover" style={this.tableStyle}>
            <thead>
            <tr>
            <th scope="col">&nbsp;</th>
              <th scope="col"></th>
              <th scope="col">Product</th>
              <th scope="col">Category</th>
              <th scope="col">Unit Price</th>
              <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {records.map(record =>
              <tr key={record.name}>
                <td>
                  <img src={record.thumbnailImage} alt="Item image"></img>
                </td>
                <td>{record.name}</td>
                <td>{record.categoryPath}</td>
                <td>${record.salePrice}</td>
                <td>
                  <button 
                    className="btn btn-primary"
                    onClick={(e) => this.onClickSelectItem(record, e)} > Select </button>
                </td>
              </tr>
            )}
  
            </tbody>
          </table>
        </div>
      );
    }
  }
  
  export default ItemSearch;
